export const data = [
    {
        id:"443j342332" ,
        image: "https://images-na.ssl-images-amazon.com/images/I/51Zymoq7UnL._AC_SY400_.jpg",    
        title:"The lean startup",
        price:29.99,
        rating:3
    },
    {   
        id:"4214j2124",
        image:"https://m.media-amazon.com/images/I/61UdeL7aO-L._AC_UL480_QL65_.jpg",
        title:"Amazon Basics 48 Pack AA High-Performance Alkaline Batteries, 10-Year Shelf Life, Easy to Open Value Pack",
        price:219.99,
        rating:1,
    },
    {   
        id:"715173572",
        image:"https://m.media-amazon.com/images/I/71wrIZujPIL._AC_UL480_QL65_.jpg",
        title:"EltaMD UV Clear Facial Sunscreen Broad-Spectrum SPF 46 for Sensitive or Acne-Prone Skin, Oil-free",
        price:164.99,
        rating:5,
    },
    {           
        id:"29494992",
        image:"https://m.media-amazon.com/images/I/7120GgUKj3L._AC_UL480_QL65_.jpg",
        title:"Nintendo Switch Pro Controller",
        price:138.99,
        rating:3,
    },
    {       
        id:"9493011",
        image:"https://m.media-amazon.com/images/I/61drpi3cYUL._AC_UL480_QL65_.jpg",
        title:"Amazon Basics 36 Pack AAA High-Performance Alkaline Batteries, 10-Year Shelf Life, Easy to Open Value Pack",
        price:212.99,
        rating:4,
    },
    {
        id:"0393211",
        image:"https://m.media-amazon.com/images/I/71rXSVqET9L._AC_UL480_QL65_.jpg",
        title:"Victrola Vintage 3-Speed Bluetooth Portable Suitcase Record Player with Built-in Speakers | Upgraded Turntable Audio Sound| Includes Extra Stylus",
        price:245.99,
        rating:4,
    },
    {
        id:"3124443",
        image:"https://m.media-amazon.com/images/I/717dWfmxXVL._AC_UL480_QL65_.jpg",
        title:"Roku Express | HD Streaming Media Player with High Speed HDMI Cable and Simple Remote",
        price: 545.99,
        rating: 5,
    },
    {
        id:"1244531",
        image:"https://m.media-amazon.com/images/I/71Llge105IL._AC_UL480_QL65_.jpg",
        title:"Original HP 67XL Black High-yield Ink Cartridge | Works with HP DeskJet 1255, 2700, 4100 Series, HP ENVY 6000, 6400 Series | Eligible for Instant",
        price:181.99,
        rating: 4,
    },
    {
        id:"1234033",
        image:"https://m.media-amazon.com/images/I/81tjLksKixL._AC_UL480_QL65_.jpg",
        title:"Seagate Portable 2TB External Hard Drive Portable HDD – USB 3.0 for PC, Mac, PlayStation, & Xbox - 1-Year Rescue Service (STGX2000400)",
        price: 872.99,
        rating:4,
    },
]